### ISSUE TITLE
How to use cache in github action when using dip

### ISSUE THREAD

**Issue by j-manu** [evilmartians/ruby-on-whales#20]
Reference
* https://evilmartians.com/chronicles/journey-from-circleci-to-github-actions
* https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development

When using `dip.yml` it is convenient to use it in github actions as well. Example from a repo of mine
```yaml
    - name: Build Images
        run: dip build
        shell: bash

      - name: Pull Images
        run: dip compose pull redis minio caddy  
        shell: bash
      
      - name: Provision
        run: touch .dockerdev/.bashrc && dip provision
        shell: bash

      - name: Integration Tests
        run: dip test system
        shell: bash
```

By default this doesn't cache the images created in `dip build` step. How can we do that?
